# Deep Learning in Medicine
### BMSC-GA 4493, BMIN-GA 3007 
### Lab 1: PyTorch Tutorial and Loss Functions


### Goal of this lab: 
    - Understand Pytorch Tensor, and AutoGrad (Variable is deprecated in the new version of pytorch). 
    - Understand Loss Functions

### What is PyTorch?
It's a Python based scientific computing package targeted as:
* A replacement for numpy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed

### Tensor
It is similar to Numpy Ndarray
<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html 


In [1]:
from __future__ import print_function
import torch

#### Check Version of the Pytorch

In [3]:
print(torch.__version__)

1.4.0


#### Tensor Initialization

In [4]:
x = torch.Tensor(6, 2)  # construct a 6x2 matrix, uninitialized

In [5]:
x, x.size()

(tensor([[0.0000e+00, 4.6566e-10],
         [0.0000e+00, 4.6566e-10],
         [1.4569e-19, 6.4069e+02],
         [4.3066e+21, 1.1824e+22],
         [4.3066e+21, 6.3828e+28],
         [3.8016e-39, 0.0000e+00]]), torch.Size([6, 2]))

In [6]:
y = torch.rand(6, 2)  # construct a randomly initialized matrix


In [7]:
y, y.size()

(tensor([[0.2309, 0.5449],
         [0.6614, 0.2085],
         [0.2808, 0.2294],
         [0.1945, 0.1787],
         [0.7921, 0.2889],
         [0.5485, 0.5955]]), torch.Size([6, 2]))

In [8]:
z = torch.ones(7) # construct a matrix of ones

In [9]:
z, z.size()

(tensor([1., 1., 1., 1., 1., 1., 1.]), torch.Size([7]))

#### Operation Example: Addtion
Related reading and reference:
    
* PyTorch documentation:
<a href="https://pytorch.org/docs/stable/nn.html"> https://pytorch.org/docs/stable/nn.html </a>

In [10]:
# addition: syntax 1
x + y

tensor([[2.3094e-01, 5.4488e-01],
        [6.6137e-01, 2.0854e-01],
        [2.8085e-01, 6.4092e+02],
        [4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28],
        [5.4846e-01, 5.9552e-01]])

In [11]:
# addition: syntax 2
torch.add(x, y)

tensor([[2.3094e-01, 5.4488e-01],
        [6.6137e-01, 2.0854e-01],
        [2.8085e-01, 6.4092e+02],
        [4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28],
        [5.4846e-01, 5.9552e-01]])

In [12]:
# addition: giving an output tensor
result = torch.Tensor(6, 2)
torch.add(x, y, out=result)

tensor([[2.3094e-01, 5.4488e-01],
        [6.6137e-01, 2.0854e-01],
        [2.8085e-01, 6.4092e+02],
        [4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28],
        [5.4846e-01, 5.9552e-01]])

In [13]:
# addition: in-place
y.add_(x) # adds x to y

tensor([[2.3094e-01, 5.4488e-01],
        [6.6137e-01, 2.0854e-01],
        [2.8085e-01, 6.4092e+02],
        [4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28],
        [5.4846e-01, 5.9552e-01]])

#### Numpy Bridge:
The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

##### Convert Torch Tensor to Numpy

In [14]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [15]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [16]:
a.add_(1) # Remember this is an inplace addition
print(a)
print(b) # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Converting Numpy Array to Torch Tensor

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


####  Used of CUDA

In [18]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

### Autograd: automatic differentiation
* The autograd package provides automatic differentiation for all operations on Tensors.It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

### Tensor
* torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it.
* When you finish your computation you can call .backward() and have all the gradients computed automatically.
* The gradient for this tensor will be accumulated into .grad attribute.
* To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

### Function
* Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation.
* Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

Related Reading and Reference:
<a href="https://pytorch.org/docs/stable/autograd.html"> https://pytorch.org/docs/stable/autograd.html </a>

In [19]:
import torch

In [28]:
x = torch.ones((2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [29]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [30]:
print(y.grad_fn)

In [31]:
z = y * y * 2
out = z.mean()
print(z, out)

tensor([[18., 18.],
        [18., 18.]], grad_fn=<MulBackward0>) tensor(18., grad_fn=<MeanBackward0>)


In [32]:
# What's the gradient of X before backward() is performed?
print(x.grad)

None


In [33]:
# What's the correct gradient of X?
out.backward()
print(x.grad)
# Question: How do we get these values?

tensor([[3., 3.],
        [3., 3.]])


In [34]:
print(y.grad)

None


In [35]:
y.retain_grad()
# look into this further . it has to to with retaining the output of the calcuations 

In [ ]:
XXXXX???

In [36]:
print(y.grad)

None


In [ ]:
print(y.grad)

### Loss Functions

 Related Reference: 
<a href="http://pytorch.org/docs/master/nn.html#loss-functions">http://pytorch.org/docs/master/nn.html#loss-functions </a>

#### Mean Squared Error
Question: What is mean square error? What are the inputs? What's the output?

In [37]:
import torch.nn as nn
input = torch.randn((4, 5), requires_grad=True)
target = torch.randn(4, 5)

In [38]:
print(input)
print(target)

tensor([[-1.0852,  0.5568, -0.1495,  0.2780,  2.2552],
        [-0.4002,  0.5491,  0.3517, -0.6537,  0.5319],
        [-1.1120,  1.1089, -1.3266, -1.4440,  0.1758],
        [ 0.6074,  0.3505,  0.5556, -1.9860, -0.0086]], requires_grad=True)
tensor([[ 0.0408, -2.5269, -1.1681,  1.0881,  0.4063],
        [ 0.1860,  1.6593,  0.6384,  0.2547, -0.1404],
        [ 0.1888, -2.1351, -1.4505,  0.4329, -1.0814],
        [-0.0151,  0.6146,  1.9194, -0.0878, -1.3027]])


In [39]:
loss = nn.MSELoss()
output = loss(input, target)
output.backward()

In [40]:
output, input

(tensor(2.1877, grad_fn=<MseLossBackward>),
 tensor([[-1.0852,  0.5568, -0.1495,  0.2780,  2.2552],
         [-0.4002,  0.5491,  0.3517, -0.6537,  0.5319],
         [-1.1120,  1.1089, -1.3266, -1.4440,  0.1758],
         [ 0.6074,  0.3505,  0.5556, -1.9860, -0.0086]], requires_grad=True))

#### Cross Entropy Loss
Question: What is cross entropy loss? What are the inputs? What's the output?

In [41]:
input = torch.randn((4, 5), requires_grad=True)
target = torch.LongTensor(4).random_(5)
print(input)
print(target)

tensor([[-0.3492,  0.3110,  0.0525, -0.0385, -1.4016],
        [ 0.5166, -0.9682, -0.0888,  0.3974, -0.0166],
        [-0.8403,  1.9231,  0.6849, -0.0789,  1.6644],
        [ 0.9481, -0.1975, -0.5113, -0.9282, -0.9327]], requires_grad=True)
tensor([1, 0, 0, 2])


In [45]:
loss = nn.CrossEntropyLoss()
output = loss(input, target)
output.backward()

In [46]:
output, input

(tensor(1.9974, grad_fn=<NllLossBackward>),
 tensor([[-0.3492,  0.3110,  0.0525, -0.0385, -1.4016],
         [ 0.5166, -0.9682, -0.0888,  0.3974, -0.0166],
         [-0.8403,  1.9231,  0.6849, -0.0789,  1.6644],
         [ 0.9481, -0.1975, -0.5113, -0.9282, -0.9327]], requires_grad=True))

### Reference:
* Deep Learning with PyTorch: A 60 Minute Blitz:
    <a href="http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html">http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
    
    
* PyTorch documentation:
<a href="https://pytorch.org/docs/stable/nn.html"> https://pytorch.org/docs/stable/nn.html </a>